name: my first workflow
on: [workflow_dispatch, push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: sofusalbertsen/custom-action@main
        with:
          myInput: sofus
